# Generated by Django 3.1.7 on 2021-05-26 12:15

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSms',
            fields=[
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='휴대폰 번호')),
                ('auth_number', models.IntegerField(verbose_name='인증 번호')),
            ],
            options={
                'db_table': 'auth_numbers',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_prop', models.CharField(choices=[('NOT', 'Not Yet'), ('PRO', 'In Progress'), ('COM', 'Complete')], default=1, max_length=10)),
                ('contract', models.BooleanField(default=False)),
                ('contract2', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datentime', models.DateTimeField()),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('banner_photo', models.ImageField(upload_to=api.models.Notice.upload_banner)),
                ('content_photo', models.ImageField(blank=True, null=True, upload_to=api.models.Notice.upload_contentphoto)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('Woman', '여성의류/잡화'), ('Man', '남성의류/잡화'), ('Digital', '디지털/가전'), ('MajorBook', '전공도서'), ('MajorEtc', '전공기타'), ('Game', '게임'), ('Sports', '스포츠'), ('Household', '생활잡화'), ('Etc', '기타')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('caution', models.TextField()),
                ('price', models.IntegerField()),
                ('price_prop', models.CharField(choices=[('Day', '일 당'), ('30m', '30분 당'), ('1h', '시간 당')], max_length=10)),
                ('place_option', models.BooleanField(default=True)),
                ('hits', models.IntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('product_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=api.models.Review.upload_review)),
                ('deal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.deal')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deal', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.deal')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='photo/no_image.png', null=True, upload_to=api.models.ProductPhoto.upload_photo)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ManyToManyField(blank=True, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='DealReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(choices=[('상', '상'), ('중', '중'), ('하', '하')], default=1, max_length=30)),
                ('q2', models.CharField(choices=[('상', '상'), ('중', '중'), ('하', '하')], default=1, max_length=30)),
                ('q3', models.CharField(choices=[('상', '상'), ('중', '중'), ('하', '하')], default=1, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.deal')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.CreateModel(
            name='BillrunUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('community', models.CharField(choices=[('한양', '한양대학교'), ('관리자', '기타')], max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('money', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=10)),
                ('profile', models.ImageField(blank=True, default='user/default_user.png', null=True, upload_to=api.models.BillrunUser.upload_profile)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
