# Generated by Django 3.1.7 on 2021-06-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrunuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
