# Generated by Django 3.1.7 on 2021-06-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsms',
            name='phone',
            field=models.CharField(max_length=110, unique=True, verbose_name='휴대폰 번호'),
        ),
        migrations.AlterField(
            model_name='billrunuser',
            name='community',
            field=models.CharField(choices=[('한양대', '한양대학교'), ('관리자', '관리자')], max_length=30),
        ),
        migrations.AlterField(
            model_name='billrunuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billrunuser',
            name='phone',
            field=models.CharField(max_length=110, unique=True),
        ),
    ]
