# Generated by Django 3.1.7 on 2021-06-15 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210611_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.billrunuser'),
        ),
        migrations.AddField(
            model_name='dealreview',
            name='q4',
            field=models.CharField(choices=[('상', '상'), ('중', '중'), ('하', '하')], default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='dealreview',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.billrunuser'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.billrunuser'),
        ),
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.billrunuser'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.billrunuser'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.billrunuser'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AlterField(
            model_name='dealreview',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deal'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deal'),
        ),
    ]
