# Generated by Django 3.1.6 on 2021-02-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210202_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_option',
            field=models.CharField(choices=[('F2F', 'Face to Face'), ('Untact', 'Untact')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='deal_option',
            field=models.CharField(choices=[('F2F', 'Face to Face'), ('Untact', 'Untact')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='deal_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='api.deal'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(blank=True, to='api.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
