# Generated by Django 3.1.6 on 2021-02-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210203_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deal_option',
            field=models.CharField(blank=True, choices=[('F2F', 'Face to Face'), ('Untact', 'Untact')], default='', max_length=10, null=True),
        ),
    ]
