# Generated by Django 3.1.7 on 2021-06-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210615_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealreview',
            name='q1',
            field=models.CharField(choices=[('X', 'X'), ('상', '상'), ('중', '중'), ('하', '하')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='dealreview',
            name='q2',
            field=models.CharField(choices=[('X', 'X'), ('상', '상'), ('중', '중'), ('하', '하')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='dealreview',
            name='q3',
            field=models.CharField(choices=[('X', 'X'), ('상', '상'), ('중', '중'), ('하', '하')], default=1, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dealreview',
            name='q4',
            field=models.CharField(choices=[('X', 'X'), ('상', '상'), ('중', '중'), ('하', '하')], default=1, max_length=30, null=True),
        ),
    ]
