# Generated by Django 3.1.7 on 2021-06-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210610_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrunuser',
            name='community',
            field=models.CharField(choices=[('한양대', '한양대학교'), ('관리자', '관리자')], max_length=30),
        ),
    ]
