# Generated by Django 3.1.7 on 2021-06-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210615_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='place_option',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_prop',
            field=models.CharField(choices=[('Day', '일 당'), ('1h', '시간 당'), ('1w', '주당')], max_length=10),
        ),
    ]
