# Generated by Django 3.1.7 on 2021-07-01 14:57

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210625_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrunuser',
            name='profile',
            field=models.ImageField(blank=True, default='default/default_user.png', null=True, upload_to=api.models.BillrunUser.upload_profile),
        ),
        # migrations.AlterField(
        #     model_name='productphoto',
        #     name='photo',
        #     field=models.ImageField(blank=True, default='default/no_image.png', null=True, upload_to=api.models.ProductPhoto.upload_photo),
        # ),
        # migrations.AlterField(
        #     model_name='productphoto',
        #     name='product',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.product'),
        # ),
    ]
