# Generated by Django 3.1.7 on 2021-07-01 17:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210701_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo1',
            field=models.ImageField(blank=True, default='default/no_image.png', null=True, upload_to=api.models.Product.upload_photo),
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Product.upload_photo),
        ),
        migrations.AddField(
            model_name='product',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Product.upload_photo),
        ),
        migrations.AddField(
            model_name='product',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Product.upload_photo),
        ),
        migrations.AddField(
            model_name='product',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Product.upload_photo),
        ),
    ]
