# Generated by Django 3.1.6 on 2021-02-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='contract2',
            field=models.BooleanField(default=False),
        ),
    ]
