# Generated by Django 3.1.6 on 2021-02-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_deal_contract2'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
