# Generated by Django 3.1.7 on 2021-07-01 18:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210701_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrunuser',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='billrunuser',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='billrunuser',
            name='profile',
            field=models.ImageField(default='default/default_user.png', upload_to=api.models.BillrunUser.upload_profile),
        ),
    ]
