# Generated by Django 3.1.7 on 2021-07-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210701_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrunuser',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=37.55723, max_digits=9),
        ),
        migrations.AlterField(
            model_name='billrunuser',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=127.04539, max_digits=9),
        ),
    ]
