# Generated by Django 3.1.7 on 2021-07-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210724_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=37.55723, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, default=127.04539, max_digits=9, null=True),
        ),
    ]
