# Generated by Django 3.1.7 on 2021-07-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210724_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrunuser',
            name='profile',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/billrun-314101.appspot.com/o/default%2Fdefault_u[…]?alt=media&token=08fe3895-fdce-40f9-9176-a62bde9a879b'),
        ),
    ]
