# Generated by Django 3.1.7 on 2021-04-15 21:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210414_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Review.upload_review),
        ),
    ]
