# Generated by Django 3.1.7 on 2021-07-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210724_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.URLField(default='https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Fbillrun-314101.appspot.com%2Fo%2Fdefault%252Fno_image.png%3Falt%3Dmedia%26token%3D63b79d71-65a3-4706-b9f2-23d65503e288'),
        ),
    ]
