# Generated by Django 3.1.7 on 2021-04-16 11:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='media/user/default_user.png', null=True, upload_to=api.models.User.upload_profile),
        ),
    ]
