# Generated by Django 3.1.7 on 2021-07-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210725_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/billrun-314101.appspot.com/o/default%2Fno_image.png?alt=media&token=63b79d71-65a3-4706-b9f2-23d65503e288'),
        ),
    ]
