# Generated by Django 3.1.7 on 2021-04-16 14:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210416_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('banner_photo', models.ImageField(upload_to=api.models.Notice.upload_banner)),
                ('content_photo', models.ImageField(blank=True, null=True, upload_to=api.models.Notice.upload_contentphoto)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='user/default_user.png', null=True, upload_to=api.models.User.upload_profile),
        ),
    ]
