# Generated by Django 3.1.7 on 2021-07-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210725_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrunuser',
            name='profile',
            field=models.CharField(default='default%2Fdefault_u[…]?alt=media&token=08fe3895-fdce-40f9-9176-a62bde9a879b', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.CharField(default='default%2Fno_image.png?alt=media&token=63b79d71-65a3-4706-b9f2-23d65503e288', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
