# Generated by Django 3.1.7 on 2021-04-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210416_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
