# Generated by Django 3.1.7 on 2021-08-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_chat_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrunuser',
            name='profile',
            field=models.CharField(default='default%2Fdefault_user.png?alt=media&token=08fe3895-fdce-40f9-9176-a62bde9a879b', max_length=200),
        ),
    ]
