# Generated by Django 3.1.7 on 2021-04-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_product_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSms',
            fields=[
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='휴대폰 번호')),
                ('auth_number', models.IntegerField(verbose_name='인증 번호')),
            ],
            options={
                'db_table': 'auth_numbers',
            },
        ),
    ]
