# Generated by Django 3.1.7 on 2021-04-27 15:15

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='deal_id',
            new_name='deal',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='borrow',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Woman', '여성의류/잡화'), ('Man', '남성의류/잡화'), ('Digital', '디지털/가전'), ('MajorBook', '전공도서'), ('MajorEtc', '전공기타'), ('Game', '게임'), ('Sports', '스포츠'), ('Household', '생활잡화'), ('Etc', '기타')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_prop',
            field=models.CharField(choices=[('Day', '일 당'), ('30m', '30분 당'), ('1h', '시간 당')], max_length=10),
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='photo/no_image.png', null=True, upload_to=api.models.ProductPhoto.upload_photo)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
