# Generated by Django 3.1.7 on 2021-05-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210429_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='borrow',
            new_name='lend',
        ),
    ]
